baseURL = "http://www.datatheque.com/"
languageCode = "en-us"
title = "datathèque"
publishDir = "docs"

[[menu.main]]
    name = "About Me"
    weight = -110
    identifier = "about"
    url = "/about/"
